### ISSUE TITLE
Species found in 'gisd' but not in 'all' using command eol

### ISSUE THREAD

**Issue by Martin-Jung** [ropenscilabs/originr#10]
Using the example code provided in the help:

This finds 2 records
```
library(originr)
  eol(name=c('Lymantria dispar','Cygnus olor','Hydrilla verticillata','Pinus concolor'),
      dataset='gisd',count = T)
>2
```
However the same command using dataset ='all' finds none
```
  eol(name=c('Lymantria dispar','Cygnus olor','Hydrilla verticillata','Pinus concolor'),
      dataset='all',count = T)
>0
```
Given that the description says "all == All datasets", this appears weird to me ?

**Comment by sckott** [comment]
thanks @Martin-Jung  - I'll have a look , their API is down right now, but will try again when they're back up

**Comment by sckott** [comment]
@Martin-Jung So drilled down into EOL API and it turns out paging in their API doesn't work at all - so that's really great 😡 😡 :rage4: 

i'm trying to get them to fix it, we'll see

**Comment by sckott** [comment]
@Martin-Jung heard back from them on twitter https://twitter.com/eol/status/835229935769894912 - not sure how to know when it's fixed, will check again soon
