### ISSUE TITLE
is_native returns errors for some species

### ISSUE THREAD

**Issue by Martin-Jung** [ropenscilabs/originr#12]
Example:

```
library(originr)
is_native("Bombus occidentalis",where = "Continental US",region = "america")

```
**Error in data.frame(name = sp, origin = Out, stringsAsFactors = FALSE) : 
  arguments imply differing number of rows: 1, 0**

_Bombus occidentalis_ should be native in the US (or return not included in itis as they don't seem to capture invertebrates well).

**Comment by sckott** [comment]
thanks @Martin-Jung fixed, and require newest version of `taxize`
