### ISSUE TITLE
Add fishbase?

### ISSUE THREAD

**Issue by ibartomeus** [ropenscilabs/originr#14]
Fishbase has data on fish introductions. We can use `rfishbase` and just call two functions from the package:

```
introductions("Alburnus alburnus")
faoareas("Alburnus alburnus")
#idem: distribution("Alburnus alburnus")
```

Two other functions would be nice, but would need a bit more of work:

1) Search origin by species `country(fish)` would need to translate the `CountryRefNo` or `c_code` to the actual country. I can't find where this is stored. Sorry. Maybe @cboettig can point me out where?

2) Search by country. Here I am even more lost. `c_code(c_code = "724")` returns the same list of species (`SpecCode`) regardless of the code passed (`c_code(c_code = "Spain") or c_code(c_code = "France")`).

What do you think?

**Comment by sckott** [comment]
Sounds good @ibartomeus

**Comment by cboettig** [comment]
@sckott there should be a countryref endpoint to translate those codes, but not seeing it in the API.  We do have countrysub  and countrysubref  endpoints. Can you take a quick look and see if that table is in the DB and if so E can expose it?


One day rfishbase / and / or the API should probably handle resolving the ref tables automatically...

**Comment by sckott** [comment]
yeah, will look. 

@cboettig what do you mean by this:

> handle resolving the ref tables automatically

**Comment by cboettig** [comment]
Thanks.  A lot of tables in FishBase return what @ibartomeus notes for countries, where the country is just given as an ID number, so to know what country it is you need to look it up in a separate table (like countryref or faoareasref).  Of course this makes sense from a database standpoint (the ref tables usually have additional information beyond the name of the country / area etc), but at least for the R user it would probably make more sense to just automatically retrieve any referenced table and go ahead and do a table join on the relevant id number.

**Comment by sckott** [comment]
okay, so for joining - do that on the API side - or in `rfishbase`?

**Comment by cboettig** [comment]
Good question, probably fine just on the R side

**Comment by sckott** [comment]
The package will be archived due to not being used very much. Closing the issue
