### ISSUE TITLE
eol() 'all' option may not be working

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/originr#18]
https://gist.github.com/sckott/0951ef11dc6d2e22744e6b030fded3dd

**Comment by ibartomeus** [comment]
Any advance on this front? Thanks!

**Comment by sckott** [comment]
no, i haven't looked at it yet 😞

**Comment by sckott** [comment]
looked at it again, i think this is just the behavior EOL has. When using `all`, you don't get the individual database names in the result
