### ISSUE TITLE
nsr() needs error message when country is misspelled

### ISSUE THREAD

**Issue by ibartomeus** [ropenscilabs/originr#19]
```
nsr(c("Pinus ponderosa", "Poa annua"), "United States") #ok
nsr(c("Pinus ponderosa", "Poa annua"), "United State") #return blank dataframe
```

And I can't find a list of valid country names. A link to accepted country names in the help may be cool.

**Comment by sckott** [comment]
asked the maintainer about this.

**Comment by ibartomeus** [comment]
Thanks, I am happy to add those to the help once we know them.

**Comment by sckott** [comment]
thanks, assigned you

**Comment by ojalaquellueva** [comment]
Hi, developer of the NSR here. Comment noted. NSR assumes taxon names and political division names are correct and have been standardized. For BIEN (http://bien.nceas.ucsb.edu/bien/) the steps are handled separately. Taxon names are processed by the TNRS. We are working on a political division name standardization service (GNRS: Geographic Name Resolution Service).

**Comment by ojalaquellueva** [comment]
Just sent a list of NSR country names to Scott.

**Comment by sckott** [comment]
thanks @ojalaquellueva - and got email
