### ISSUE TITLE
Appveyor badge and webhook

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/originr#24]
:wave: @sckott!

* The badge points to ropensci Appveyor account but builds are at https://ci.appveyor.com/project/sckott/originr

* Appveyor deliveries have been consistently failing for a while. 😭  You'll need to email Appveyor team 🎊 at  team@appveyor.com and mention this about the latest delivery
    X-GitHub-Delivery: e38d92bc-4d4e-11e8-9053-d7924decbf9b
    Time: 2018-05-01 16:49:45

Thank you!

**Comment by maelle** [comment]
Maybe try that first (email received this night from Appveyor)

* New commit and push (the "account" was blocked, unclear to me whether they mean Appveyor or GitHub...)

*  If you believe that you need to re-create webhook, you can find correct Webhook URL on General project settings in AppVeyor UI. Use it when creating a Webhook on GitHub. Select “Push” and “Pull request” events. You can also delete unneeded webhook manually on GitHub. Or you can create new project on AppVeyor and correct webhook will be created automatically.

 *   If repo owner changed, you can may also need to re-authorize GitHub at https://ci.appveyor.com/account.

**Comment by sckott** [comment]
should be fixed now
