### ISSUE TITLE
Expand griis function to cover all countries covered by GRIIS

### ISSUE THREAD

**Issue by RonjaRaeningidottir** [ropenscilabs/originr#27]
The **griis()** function currently covers 122 countries. However, the article "Introducing the Global Register of Introduced and Invasive Species" states that information is available for 198 countries. Missing are for example "Sweden". Looking forward to seeing this package grow! very useful for me :) 

<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by sckott** [comment]
Thanks for the issue!  Can you share a link for what you're talking about?

**Comment by RonjaRaeningidottir** [comment]
If you go to [http://www.griis.org/sources.php]( http://www.griis.org/sources.php) you can see a list of all the countries they cover by now. There are more countries on that list, than listed in the **countries** variable of your function.

**Comment by sckott** [comment]
Yes, looks like there's many more countries we don't have. will add those soon.

**Comment by ibartomeus** [comment]
Thanks sckott!

**Comment by sckott** [comment]
The package will be archived due to not being used very much. Closing the issue
