### ISSUE TITLE
heads up

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/originr#3]
@ibartomeus moved fxns about whether species are native or invasive to a sep package, this one - added you as author. chime in if you have any thoughts 

will close this soon, just letting you know

**Comment by ibartomeus** [comment]
Thanks @sckott I see this functions keeps moving from package to package, but this looks like a permanent good home. Happy to keep collaborating, just let me know if there are things to be done.

**Comment by sckott** [comment]
> this looks like a permanent good home.

Yes, it is for these functions

> let me know if there are things to be done.

will do
