### ISSUE TITLE
GRIIS

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/originr#5]
http://www.griis.org/search3.php

via https://twitter.com/frod_san/status/725951339264516097

**Comment by sckott** [comment]
One way to get data is they provide a csv dump of data once you search, and the url to get the csv has parameters

**Comment by sckott** [comment]
cc @ibartomeus

**Comment by ibartomeus** [comment]
Seems feasible. Would be a good idea to put all data as Rdata in a package, along with a function to update this data? or it's better to only use queries?

I can help if you want, but not until July.

**Comment by sckott** [comment]
Hmm, I think it's better to just do queries so as we avoid actually holding the data and distributing it - avoiding any potential terms violations 

> I can help if you want, but not until July.

I can get it done soon :)

**Comment by ibartomeus** [comment]
You are too fast (and good) for me to be able to contribute, thanks skott!

**Comment by sckott** [comment]
Having said I can do it, there is no rush to get it in - let me know if you want to do - I do have plenty other work to do :)

**Comment by ibartomeus** [comment]
I'll try to do a first attempt then.

On Fri, Apr 29, 2016 at 10:24 AM Scott Chamberlain notifications@github.com
wrote:

> Having said I can do it, there is no rush to get it in - let me know if
> you want to do - I do have plenty other work to do :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/ropenscilabs/originr/issues/5#issuecomment-215656913
> 
> ## 
> 
> ## 
> 
> Ignasi Bartomeus PhD
> www.bartomeuslab.com
> @ibartomeus
> Skype: nachobartomeus

Dpto. Ecología Integrativa
Estación Biológica de Doñana (EBD-CSIC)
Avda. Américo Vespucio s/n
Isla de la Cartuja
41092, Sevilla (Spain)
