### ISSUE TITLE
Flora Europaea inaccessible

### ISSUE THREAD

**Issue by Alectoria** [ropenscilabs/originr#9]
Access to the Flora Europaea homepage [http://rbg-web2.rbge.org.uk/FE/fe.html]
is now redirected to the Euro+Med homepage :-(

**Comment by sckott** [comment]
thanks for the note on this, looking into it

**Comment by sckott** [comment]
`flora_europaea` still works fine, any thoughts @ibartomeus

**Comment by ibartomeus** [comment]
No idea, seems they are updating things. That's the problem with web scraping. I don't know for how long the old interface for which the function works will be available (so far so good). The new webpage seems also scrapable, but I would wait to see what happens.

**Comment by sckott** [comment]
this still works, so closing this
